### ISSUE TITLE
Research and adjust licensing

### ISSUE THREAD

**Issue by Brewing1** [online-bridge-hackathon/DDS#6] opened 2020-05-23 18:05 UTC
https://github.com/dds-bridge/dds/ has an apache-2 license.
Note that we have actually used this fork https://github.com/df7cb/dds/commits/linux-memory which fixed a bug in the original repo.

The question is, can we convert this repo to an MIL license, whilst using this (fork of the) library? Currently we have Apache-2 on this repo.

**Comment by tameware** [comment] 2020-05-23 19:49
You mean MIT license, right? I'll go read up on Apache-2. I've heard conflicting things about how similar Apache and MIT are.

**Comment by tameware** [comment] 2020-05-23 19:54
Reading the license I think we are in the clear:

http://www.apache.org/licenses/LICENSE-2.0

"4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:"

As I understand things we don't intend to redistribute the dds C++ code, just deploy it to one or more servers. Anyone who wants to build on our efforts will have to download the source from GitHub and compile their own version, as each of us have done.

**Comment by angshenting** [comment] 2020-06-20 10:37
Closing as the issue seems to be resolved.

**Closed** 2020-06-20 10:36 UTC
